PI/urls.py
from django.contrib import admin
from django.urls import path, include
from venda import views 
from . import settings
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_usuario), 
    path('cadastro/', views.usuario_registro),
    path('cadastro/submit', views.set_usuario),
    path('login/submit', views.submit_login), 
    path('logout/', views.logout_usuario),
    path('feitoLogin/',views.index),
    path('sobre/', views.sobre),
    path('produto/', views.lista_produtos),
    path('produto/pm/', views.lista_placamae),
    path('produto/pr/', views.lista_processador),
    path('produto/pv/', views.lista_placavideo),
    path('produto/dr/', views.lista_discorigido),
    path('produto/fo/', views.lista_fontes),
    path('produto/mr/', views.lista_memoriaram),
    path('produto/finalizar/<id>/', views.finalizar_produto),
    path('produto/finalizar/<id>/submit', views.comprar),
    path('produto/todos', views.lista_produtos),
    path('detalhe/<id>/',views.produto_detail),
    path('detalhe/<id>/submit',views.addcarrinho),
    path('produto/registro/', views.historia_registro),
    path('produto/registro/submit', views.set_historia),
    path('produto/deletar/<id>/', views.deletar_produto),
    path('', RedirectView.as_view(url='produto/')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

venda/urls.py
from django.urls import path
from .views import lista_produtos, criar_produto, atualizar_produto, deletar_produto

urlpatterns = [
    path ('',lista_produtos, name = 'lista_produtos' ),
    path ('Novo', criar_produto, name = 'criar_produto'),
    path ('atualizar/<int:id>/', atualizar_produto, name = 'atualizar_produto'),
    path ('deletar/<int:id>/', deletar_produto, name = 'deletar_produto'),
]

venda/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Produto(models.Model):
    PlacaMae = 'PM'
    Processador = 'PR'
    Fonte = 'FO'
    PlacadeVideo = 'PV'
    DiscoRigido = 'DR'
    MemoriaRAM = 'MR'
    TIPO_DE_PRODUTO_CHOICES = [
        (PlacaMae, 'Placa Mãe'),
        (Processador, 'Processador'),
        (Fonte, 'Fonte'),
        (PlacadeVideo, 'Placa de Vídeo'),
        (DiscoRigido, 'Disco Rígido'),
        (MemoriaRAM, 'Memória RAM'),
    ]
    tipo_de_produto = models.CharField(
        max_length=2,
        choices=TIPO_DE_PRODUTO_CHOICES,
        default=PlacaMae,
    )
    nome = models.CharField(max_length = 20)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits = 9, decimal_places = 2)
    qant = models.IntegerField()
    imagem = models.ImageField(upload_to='produtos')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Usuario(models.Model):
    nome = models.CharField(max_length = 40)
    email = models.CharField(max_length = 30)
    login = models.CharField(max_length = 15)
    senha = models.CharField(max_length = 15)
    datanasc = models.DateField(auto_now=True)

    def __str__(self):
        return self.description # pylint: disable=maybe-no-member 
    def is_upperclass(self):
        return self.tipo_de_produto in (self.DiscoRigido, self.MemoriaRAM)  # pylint: disable=maybe-no-member 
class Historico (models.Model): #orderitem
    nome = models.CharField(max_length = 20)
    preco = models.DecimalField(max_digits = 9, decimal_places = 2)
    data = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.produto.nome # pylint: disable=maybe-no-member 

class Carrinho(models.Model):#order
    ref_code = models.CharField(max_length=15)
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)
    items = models.ManyToManyField(Historico)

    def get_cart_items(self):
        return self.items.all() # pylint: disable=maybe-no-member 

    def get_cart_total(self):
        return sum([items.produto.preco for items in self.items.all()]) # pylint: disable=maybe-no-member 

    def __str__(self):
        return '{0} - {1}'.format(self.usuario,self.ref_code)


class Transacao(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=120)
    total = models.DecimalField(max_digits=100, decimal_places=2)
    sucesso = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    def __str__(self):
        return self.order_id
    class Meta:
        ordering = ['-timestamp']
    
class Historia(models.Model):
    nome = models.CharField(max_length = 40)
    Romance = 'RO'
    Drama = 'DR'
    Aventura = 'AV'
    Terror = 'TE'
    TIPO_DE_GENERO_CHOICES = [
        (Romance, 'Romance'),
        (Drama, 'Drama'),
        (Aventura, 'Aventura'),
        (Terror, 'Terror'),
    ]
    tipo_de_genero = models.CharField(
        max_length=2,
        choices=TIPO_DE_GENERO_CHOICES,
        default=Aventura,
    )
    classificacao = models.IntegerField()
    preco = models.DecimalField(max_digits = 9, decimal_places = 2)
    descricao = models.TextField()
    avaliacao = models.BooleanField(default=True)
    imagem = models.ImageField(upload_to='historia', default=False)

venda/forms.py
from django import forms
from .models import Produto, Usuario

class ProdutoForm (forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['tipo_de_produto','nome','descricao','preco','qant','imagem']

venda/views.py
from django.shortcuts import render,redirect
from .models import Usuario,Produto,Historico,Historia
from .forms import ProdutoForm
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages, admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User



# Create your views here.


@login_required(login_url='/login/')
def index(request):
    venda = Historico.objects.filter(user=request.user) # pylint: disable=maybe-no-member
    return render(request, 'feitoLogin.html', {'venda':venda})

def logout_usuario(request):
    logout(request)
    return redirect('/login/')
def login_usuario(request):
    return render(request, 'login.html')

@csrf_protect
def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('/feitoLogin/')
        else:
            messages.error(request,'Usuário e/ou senha inválidas, tenta novamente. ')
            return redirect('/login/')


        


def lista_produtos (request):
    venda = Produto.objects.all() # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )

def lista_placamae(request):
    venda = Produto.objects.filter(tipo_de_produto='PM') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )
    
def lista_processador(request):
    venda = Produto.objects.filter(tipo_de_produto='PR') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )
    
def lista_fontes(request):
    venda = Produto.objects.filter(tipo_de_produto='FO') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )

    
def lista_placavideo(request):
    venda = Produto.objects.filter(tipo_de_produto='PV') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )

    
def lista_discorigido(request):
    venda = Produto.objects.filter(tipo_de_produto='DR') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )

    
def lista_memoriaram(request):
    venda = Produto.objects.filter(tipo_de_produto='MR') # pylint: disable=maybe-no-member
    return render(request,'Home.html',{'venda':venda} )


def criar_produto (request):
    form = ProdutoForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect ('lista_produtos')
    
    return render ( request,'cadastroProduto.html',{'form' : form})

def atualizar_produto (request, id):
    venda = Produto.objects.get(id=id)  # pylint: disable=maybe-no-member
    form = ProdutoForm(request.POST or None, instance = venda)

    if form.is_valid():
        form.save()
        return redirect('/')
    
    return render(request, 'cadastroProduto.html',{'form': form, 'venda': venda})



@login_required(login_url='/login/')
def deletar_produto (request, id):
    venda = Produto.objects.get(id=id)  # pylint: disable=maybe-no-member
    venda.delete()
    
    return redirect('/')

def produto_detail(request, id):
    venda = Produto.objects.get(id=id) # pylint: disable=maybe-no-member
    return render(request,'produtoDetail.html',{'venda': venda})

@login_required(login_url='/login/')
def historia_registro(request):
    historia_id = request.GET.get('id')
    if historia_id:
        venda = Historia.objects.get(id=historia_id) # pylint: disable=maybe-no-member
        return render(request,'cadastroHistoria.html', {'venda':venda})
    return render(request,'cadastroHistoria.html')

@login_required(login_url='/login/')
def set_historia(request):
    tipogenero = request.POST.get('tipogenero')
    autor = request.POST.get('autor')
    nome = request.POST.get('nome')
    descricao = request.POST.get('descricao')
    preco = request.POST.get('preco')
    classificacao = request.POST.get('classificacao')
    imagem = request.FILES.get('imagem')
    historiaid = request.POST.get('historia.id')
    if historiaid:
        venda = Historia.objects.get(id=historiaid)# pylint: disable=maybe-no-member
        print(historiaid)
        venda.tipogenero = tipogenero
        venda.autor = autor
        venda.nome = nome
        venda.descricao = descricao
        venda.preco = preco
        venda.classificacao = classificacao
        if imagem:
            venda.imagem = imagem
        venda.save()
    else: 
        print(historiaid)
        venda = Historia.objects.create(tipo_de_genero=tipogenero, autor=autor, nome=nome, descricao=descricao, preco=preco,imagem=imagem, classificacao=classificacao) # pylint: disable=maybe-no-member
    
    return redirect('/')

def inicio(request):
    return render(request,'Home.html')

def usuario_registro(request):
    return render(request,'cadastro.html')

def set_usuario(request):
    logout(request) 
    nome = request.POST.get('nome')
    email = request.POST.get('email')
    senha = request.POST.get('senha')
    csenha = request.POST.get('csenha')
    if senha == csenha:
        if senha != "":
            user = User.objects.create_user(username=nome, email=email, password=senha)
            user.save()
            usuario = authenticate(username=nome, password=senha)
            login(request, user)
            return redirect('/feitoLogin/')
        else:
            messages.error(request,'Usuário e/ou senha inválidas, tenta novamente. ')
            return redirect('/cadastro/')
    else:
        messages.error(request,'Usuário e/ou senha inválidas, tenta novamente. ')
        return redirect('/cadastro/')

    return redirect('/')

def addcarrinho(request, id):
    user = request.user 
    return redirect('/')

def sobre(request):
    return render(request, 'sobre.html')
@login_required(login_url='/login/')
def finalizar_produto(request,id):
    venda = Produto.objects.get(id=id) # pylint: disable=maybe-no-member
    return render(request, 'finalizar.html',{'venda': venda})

def comprar(request,id):
    user = request.user
    nome = request.POST.get('venda.nome')
    preco = request.POST.get(('venda.preco'))
    venda = Historico.objects.create(nome=nome, preco=preco,user=user) # pylint: disable=maybe-no-member
    return redirect('/')

venda/templates/Home.html
<!DOCTYPE html>
<html>
  <style>
    div.polaroid {
        width: 250px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        text-align: center;
    }
    div.container {
        padding: 10px;
    }
</style>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Uniparts</title>
  <link rel="icon">
</head>

<body>
  <header>
    {% include "model-nav.html" %}
  </header>
  <section>
    <div id="carouselExampleCaptions" class="carousel slide my-0" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://www.pichauarena.com.br/wp-content/uploads/2020/01/PC-Gamer-IDEAL-roda-TUDO-por-2000-Reais.jpg" class="d-block w-100" alt="..." style="">
          <div class="carousel-caption d-none d-md-block">
            <h2>Aproveite as ofertas exclusivas</h2>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://www.pichauarena.com.br/wp-content/uploads/2020/01/PC-Gamer-2600-reais-roda-tudo-em-Full-HD.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h2></h2>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://blog.intelbras.com.br/wp-content/uploads/2019/10/nobreak-ideal-para-pc-gamer.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h2></h2>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6">
              <div class="list-group">
                <a href="/produto/pr/" class="list-group-item list-group-item-action"><b> Processador<br></b></a>
                <a href="/produto/pv/" class="list-group-item list-group-item-action"><b> Placa de vídeo<br></b></a>
                <a href="/produto/mr/" class="list-group-item list-group-item-action"><b> Memória RAM<br></b></a>
              </div>
            </div>
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-12">
                  <div class="list-group">
                    <a href="/produto/dr/" class="list-group-item list-group-item-action"><b> Disco rídigo(HD)<br></b></a>
                    <a href="/produto/pm/" class="list-group-item list-group-item-action"><b> Placa Mãe<br></b></a>
                    <a href="/produto/fo/" class="list-group-item list-group-item-action"><b> Fontes<br></b></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
        {% for v in venda %}
            <div class="col-sm-3">
                <a href="/detalhe/{{ v.id }}">
                    <div class="polaroid">
                        <img src="{{ v.imagem.url }}" alt="Norway" style="width:100%"></a>
                        <div class="container">
                            <p>{{ v.nome }}</p>   <p class="text-primary">R$ {{ v.preco }}</p>
                            <a href="/produto/finalizar/{{ v.id }}"><button type="button" class="btn btn-success">Comprar</button></a>
                        </div>
                    </div>
                
                <br>
            </div>                
        {% endfor %}
    </div>
  </div> 
  
  {% include "model-footer.html" %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous" style=""></script>
</body>

</html>

venda/templates/cadastroHistoria.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body>
  {% include "model-nav.html" %}
    <!-- <img src="..." class="card-img-top" alt="..."> -->
   
    <div class="container">
      <form enctype="multipart/form-data" action="submit", method="POST">{% csrf_token %}
        <input type="number" class="form-control" name="venda.id" value="{{ venda.id }}" hidden>
        <div class="form-group">
          <label for="tipogenero">Tipo de Gênero:</label>
          <select class="form-control" id="tipogenero" name="tipogenero">
            
            <option value="RO">Romance</option>

            <option value="DR">Drama</option>

            <option value="AV">Aventura</option>

            <option value="TE">Terror</option>

          </select>
        </div>
        <div class="form-group">
          <label for="autor">Autor</label>
          <input type="text" class="form-control" name="autor" placeholder="Insira um nome de Autor valido" value="{{ venda.autor }}">
        </div>
        <div class="form-group">
          <label for="nome">Nome</label>
          <input type="text" class="form-control" name="nome" placeholder="Insira um nome de Historia valido" value="{{ venda.nome }}">
        </div>
        <div class="form-group">
          <label for="descricao">Descrição</label>
          <textarea  class="form-control" rows="5" name="descricao" placeholder="Insira a descrição do produto">{{ venda.descricao }}</textarea>
        </div>
        <div class="form-group">
          <label for="preco">Preço da Historia:</label>
          <select class="form-control" id="preco" name="preco">
            
            <option value=5>5</option>

            <option value=10>10</option>

            <option value=15>15</option>

            <option value=20>20</option>

            <option value=25>25</option>

            <option value=30>30</option>

            <option value=35>35</option>

            <option value=40>40</option>

            <option value=45>45</option>

            <option value=50>50</option>

          </select>
        </div>
        <!--<div class="form-group">
          <label for="classificacao">Classificação</label>
          <input type="number" class="vIntegerField" name="classificacao" placeholder="Insira a quantidade" value="{{ venda.classificacao }}">
        </div>-->
        <div class="form-group">
          <label for="classificacao">Classificação:</label>
          <select class="form-control" id="classificacao" name="classificacao">
            
            <option value=10>10</option>

            <option value=12>12</option>

            <option value=14>14</option>

            <option value=16>16</option>

            <option value=18>18</option>

          </select>
        <div class="form-row field-imagem">    
          <div>
             <p> <a href="/media/{{ venda.imagem }}" target="_blank">Foto Atual</a></p>
              <label class="required" for="id_imagem">Imagem:</label>                  
              <input type="file" name="imagem" accept="image/*" required id="id_imagem">        
          </div>      
         </div>
        <button type="submit" class="btn d-flex flex-column btn-info">
          {% if venda %}
          Alterar
          {% else %}
          Cadastrar produto
          {% endif %}
          <br></button> 
      </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" style=""></script>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
          </p>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

venda/templates/cadastroProduto.html
<!DOCTYPE html>
<html>

<head>
  <title>Cadastrar Produto</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body>
  {% include "model-nav.html" %}
    <!-- <img src="..." class="card-img-top" alt="..."> -->
   
    <div class="container">
      <form enctype="multipart/form-data" action="submit", method="POST">{% csrf_token %}
        <input type="number" class="form-control" name="venda.id" value="{{ venda.id }}" hidden>
        <div class="form-group">
          <label for="tipoproduto">Tipo de Produto:</label>
          <select class="form-control" id="tipoproduto" name="tipoproduto">
            
            <option value="PM">Placa Mãe</option>

            <option value="PR">Processador</option>

            <option value="FO">Fonte</option>

            <option value="PV">Placa de Vídeo</option>

            <option value="DR">Disco Rígido</option>

            <option value="MR">Memória RAM</option>
          </select>
        </div>
        <div class="form-group">
          <label for="nome">Nome</label>
          <input type="text" class="form-control" name="nome" placeholder="Insira um nome valido" value="{{ venda.nome }}">
        </div>
        <div class="form-group">
          <label for="descricao">Descrição</label>
          <textarea  class="form-control" rows="5" name="descricao" placeholder="Insira a descrição do produto">{{ venda.descricao }}</textarea>
        </div>
        <div class="form-group">
          <label for="preco">Preço</label>
          <input type="number" class="form-control" step="0.01" name="preco" placeholder="Insira o Preço" value="{{ venda.preco }}">
        </div>
        <div class="form-group">
          <label for="qant">Quantidade</label>
          <input type="number" class="vIntegerField" name="qant" placeholder="Insira a quantidade" value="{{ venda.qant }}">
        </div>
        <div class="form-row field-imagem">    
          <div>
             <p> <a href="/media/{{ venda.imagem }}" target="_blank">Foto Atual</a></p>
              <label class="required" for="id_imagem">Imagem:</label>                  
              <input type="file" name="imagem" accept="image/*" required id="id_imagem">        
          </div>      
         </div>
        <button type="submit" class="btn d-flex flex-column btn-info">
          {% if venda %}
          Alterar
          {% else %}
          Cadastrar produto
          {% endif %}
          <br></button> 
      </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
          </p>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

venda/templates/feitoLogin.html
<!DOCTYPE html>
<html>
  <style>
    div.polaroid {
        width: 250px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        text-align: center;
    }
    div.container {
        padding: 10px;
    }
</style>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
  <title></title>
</head>

<body>
  {% include "model-nav.html" %}
  
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-4 text-center">Meus pedidos</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
        {% for v in venda %}
            <div class="col-sm-3">
              <div class="polaroid"> 
              <div class="container">
                  <p>{{ v.nome }}</p>   <p class="text-primary">R$ {{ v.preco }}</p>
                  <p>{{ v.data }}</p>
                 </div>
            </div>
          </div>    
            <br>
                          
        {% endfor %}
    </div>
  </div> 
  {% include "model-footer.html" %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>